import type { Metadata, Viewport } from "next";
import { Syne, DM_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { seo, siteConfig } from "@/data/content";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { CustomCursor } from "@/components/layout/CustomCursor";
import { ScrollProgress } from "@/components/layout/ScrollProgress";
import { SmoothScrollProvider } from "@/components/layout/SmoothScrollProvider";
import { AnchorScroll } from "@/components/layout/AnchorScroll";
import { FilmGrain } from "@/components/layout/FilmGrain";
import { OpeningChoreo } from "@/components/layout/OpeningChoreo";
import { ScrollTriggerLeakCounter } from "@/components/motion/ScrollTriggerLeakCounter";

/* Pre-paint gate for the choreographed opening (Phase 8). Runs before first paint
   and sets html[data-preloader="pending"] only on a first visit on a >=768px
   fine-pointer viewport with motion allowed — DESKTOP-ONLY, because any full-
   screen first-load overlay covers the LCP hero text and sinks mobile Perf below
   the 95 gate (R4/R9). Touch / mobile / reduced motion / repeat visit / no-JS
   never set it (LCP fires on the painted H1). */
const openingGate = `(function(){try{var m=window.matchMedia;if(m("(min-width:768px)").matches&&m("(pointer:fine)").matches&&!m("(prefers-reduced-motion: reduce)").matches&&!sessionStorage.getItem("jd-seen")){document.documentElement.dataset.preloader="pending"}}catch(e){}})();`;

// Loaded as the VARIABLE font (no static `weight` array) so the wght axis is
// continuous — required for the footer kinetic-weight statement
// (font-variation-settings). One variable file also replaces five static cuts.
const syne = Syne({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-syne",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
  weight: ["300", "400", "500", "600"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jetbrains",
  weight: ["400", "500"],
});

/* Single canonical fallback — matches sitemap.ts and robots.ts (plan.md §8) */
const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://jaydhakan.com";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: seo.home.title,
    template: `%s | ${siteConfig.name}`,
  },
  description: seo.home.description,
  openGraph: {
    title: seo.home.title,
    description: seo.home.description,
    url: siteUrl,
    siteName: siteConfig.name,
    // og:image is generated by app/opengraph-image.tsx (file convention).
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: seo.home.title,
    description: seo.home.description,
  },
};

export const viewport: Viewport = {
  themeColor: "#0b0b11",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // The pre-paint opening-gate script sets html[data-preloader] before React
      // hydrates; suppress the (expected, one-level) attribute mismatch warning —
      // the canonical pattern for pre-hydration <html> mutations (cf. next-themes).
      suppressHydrationWarning
      className={`${syne.variable} ${dmSans.variable} ${jetbrainsMono.variable}`}
    >
      <body className="font-body">
        {/* Pre-paint: flip the desktop opening gate before anything paints. */}
        <script
          id="jd-opening-init"
          dangerouslySetInnerHTML={{ __html: openingGate }}
        />
        {/* Skip link: first focusable element on every page (a11y spec) */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-lg focus:bg-accent-solid focus:px-4 focus:py-2 focus:text-ink"
        >
          Skip to content
        </a>
        <SmoothScrollProvider>
          {/* Static film grain at z-30 — sibling of the cursor, painted below it
              (no blend mode, so it never fights the z-60 difference cursor). */}
          <FilmGrain />
          {/* Session-once choreographed opening (z-55 overlay, desktop-gated). */}
          <OpeningChoreo />
          <AnchorScroll />
          <ScrollTriggerLeakCounter />
          <CustomCursor />
          <ScrollProgress />
          <Header />
          {children}
          <Footer />
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
