import { imageBlur } from "./image-blur";

/**
 * LQIP blur-up props for next/image (P11). Returns `placeholder="blur"` +
 * `blurDataURL` when a generated placeholder exists for the path, else `{}`
 * (next/image falls back to "empty"). Client-safe — no fs — so it works in the
 * client list/preview components too. Blur map is generated by
 * scripts/gen-placeholders.mjs; regenerate it when real images land.
 */
export function blurProps(src: string): { placeholder: "blur"; blurDataURL: string } | Record<string, never> {
  const blurDataURL = imageBlur[src];
  return blurDataURL ? { placeholder: "blur", blurDataURL } : {};
}
