// AUTO-GENERATED by scripts/gen-placeholders.mjs — do not edit by hand.
// Tiny LQIP blur placeholders keyed by public path, for next/image placeholder="blur".
export const imageBlur: Record<string, string> = {
  "/images/projects/prompt-to-site.png": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAABwAwCdASoUAA0APu1kqU2ppaOiMAgBMB2JZQAAW+tcmmk6zQAA/vKozH3uN6n+d4ekWqMjbmQAAA==",
  "/images/projects/social-scraper.png": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAwAwCdASoUAA0APu1iqk4zpaQiMAgCcB2JZQC7AC0Hml8AAP7wJroJ22dT7qbFpuxOB4KKAAA=",
  "/images/projects/search-kit.png": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZQC7ACHfkzZPCYAAAP7yqOZua6po+tk0CsU7tgJhAAAA",
  "/images/projects/zillow-harvester.png": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAwAwCdASoUAA0APu1iqk4ppaQiMAgBMB2JZQC7AC0HxMQwAP7wQdKLobXnGEBjCS08aUmeVQ4AAA==",
  "/images/projects/chatbot-creator.png": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAABwAwCdASoUAA0APu1kqU2ppaOiMAgBMB2JYwAAW+tcWhPlHAAA/vKozH3uN6n+d4fP1Aa8F1gAAA==",
  "/images/projects/cinqcare.png": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JYwAAW+tcWkgAAP7yqMx97jeqE+C7/oGrub1ZWen7UtA4q9zIAA==",
  "/images/projects/realtime-signals.png": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZQC7ACHfkzZPCYAAAP7yqOZua6po+tk0CsU7tgJhAAAA",
  "/images/projects/research-agent.png": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAABwAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JYwAAW+q8htmgKVAA/vKo1U/bczBg9dBGevNZ/stzIAAA",
  "/images/projects/catalog-etl.png": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAgCdASoUAA0APu1iqU2ppaOiMAgBMB2JZQC7AC5JAAD+8CZCt5PiRCCl8B9TxwV36V5XuMIDWAGgAAA=",
  "/images/profile/jay.jpg": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwBACdASoUABQAPu1oqk+ppiOiMBgIATAdiWMAyJgQ7/Hj5FOD8MZLB2s6AAD+7oQOT20WEih5s7ZO/fUdGN/lzVHtNr5vPjsISjHHsAAAAA=="
};
